require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisabledByDefault: false
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 3.1.5
  Exclude:
    - db/**/*
    - bin/**/*
    - lib/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2

Style/CommentAnnotation:
  Enabled: false